{% set version = "3.0.0" %}

package:
  name: mistune
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/m/mistune/mistune-{{ version }}.tar.gz
    sha256: b28444efe542cc9bb9f19fb133740ab020fe5e14fe6ffcce9576d24fbd1e5b20
  - folder: src
    url: https://github.com/lepture/mistune/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 0df4cd4ce95325a62a91972831cd56cf05ad1ed63b42c1514de28962a9a67eab

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7

test:
  source_files:
    - src/tests
  requires:
    - pytest-cov
    - pip
  imports:
    - mistune
  commands:
    - pip check
    - cd src && pytest --cov=mistune --cov-branch --cov-report=term-missing:skip-covered --cov-fail-under=98 --no-cov-on-fail

about:
  home: https://github.com/lepture/mistune
  summary: A sane and fast Markdown parser with useful plugins and renderers
  dev_url: https://github.com/lepture/mistune
  license: BSD-3-Clause
  license_file: dist/LICENSE
  license_family: BSD
  dev_url: https://github.com/lepture/mistune
  doc_url: https://mistune.lepture.com

extra:
  recipe-maintainers:
    - xylar
    - pelson
    - bollwyvl
    - ocefpaf
