{% set version = "2.0.0" %}

package:
  name: mistune
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mistune/mistune-{{ version }}.tar.gz
  sha256: de718f82db8c3730f885d576237bdc819dcbb8bc1340db378c27ba88abb2d777

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest-cov
    - python
    - pip
  imports:
    - mistune
  commands:
    - pip check
    - pytest --cov mistune --cov-report=term-missing:skip-covered --cov-fail-under=98 --no-cov-on-fail

about:
  home: https://github.com/lepture/mistune
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A sane Markdown parser with useful plugins and renderers.
  dev_url: https://github.com/lepture/mistune
  doc_url: https://mistune.readthedocs.io

extra:
  recipe-maintainers:
    - pelson
    - bollwyvl
    - ocefpaf
