{% set version = "2.0.0" %}

package:
  name: mistune
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mistune/mistune-{{ version }}.tar.gz
  sha256: de718f82db8c3730f885d576237bdc819dcbb8bc1340db378c27ba88abb2d777

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - nose
    - python
  imports:
    - mistune
  commands:
    - nosetests

about:
  home: https://github.com/lepture/mistune
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: The fastest markdown parser in pure Python.
  dev_url: https://github.com/lepture/mistune
  doc_url: https://mistune.readthedocs.io

extra:
  recipe-maintainers:
    - pelson
    - bollwyvl
    - ocefpaf
