{% set version = "3.0.2" %}

package:
  name: mistune
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mistune/mistune-{{ version }}.tar.gz
  sha256: fc7f93ded930c92394ef2cb6f04a8aabab4117a91449e72dcc8dfa646a508be8

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - mistune
  commands:
    - pip check
    - pytest -vv --color=yes --tb=long --cov=mistune --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=95

about:
  home: https://github.com/lepture/mistune
  summary: A sane and fast Markdown parser with useful plugins and renderers
  dev_url: https://github.com/lepture/mistune
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://mistune.lepture.com

extra:
  recipe-maintainers:
    - xylar
    - pelson
    - bollwyvl
    - ocefpaf
