{% set name = "mistune" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mistune-{{ version }}.tar.gz
  sha256: 59a3429db53c50b5c6bcc8a07f8848cb00d7dc8bdb431a4ab41920d201d4756e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1006

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  source_files:
    - tests
  requires:
    - nose
    - python
    - pip
  imports:
    - mistune
  commands:
    - nosetests
    - pip check

about:
  home: https://github.com/lepture/mistune
  summary: The fastest markdown parser in pure Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/lepture/mistune
  doc_url: https://mistune.readthedocs.io

extra:
  recipe-maintainers:
    - pelson
    - bollwyvl
    - ocefpaf
