{% set version = "3.1.1" %}

package:
  name: mistune
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mistune/mistune-{{ version }}.tar.gz
  sha256: e0740d635f515119f7d1feb6f9b192ee60f0cc649f80a8f944f905706a21654c

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - mistune
  commands:
    - pip check
    - coverage run --source=mistune --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=93

about:
  home: https://github.com/lepture/mistune
  summary: A sane and fast Markdown parser with useful plugins and renderers
  dev_url: https://github.com/lepture/mistune
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://mistune.lepture.com

extra:
  recipe-maintainers:
    - xylar
    - pelson
    - bollwyvl
    - ocefpaf
